global_signkey := home_directory() / ".gnupg" / "sign.key"
signkey := if path_exists(global_signkey) {
    global_signkey
} else {
    sources_dir + "/build/sign.key"
}


nfpm_local := sources_dir + "/build/tools/nfpm"
nfpm := "NFPM_KEY=\""+ signkey + "\" " + if path_exists("/usr/bin/nfpm") == "true" {
    "nfpm" 
} else { 
    nfpm_local
}

[private,linux]
prepare_dummysign:
    # ------------------------------------------------
    # Signature key not found. Will generate dummy one
    # ------------------------------------------------
    -gpg --quick-gen-key --batch --passphrase '' testsign@localhost
    gpg --armor --export-secret-keys testsign@localhost > "{{ signkey }}"

# Create build rootfs
[private,linux]
prepare_nfpm: build
    -[ ! -f "{{ signkey }}" ] && just prepare_dummysign
    rm -rf "{{ build_dir }}/usr"
    DESTDIR="{{ build_dir }}/usr" just install
    find "{{ build_dir }}" -type d -name "__pycache__" -exec rm -r {} +

# Create Debian package
[group("os_linux")]
debian: 
    PYTHONLIBPATH="lib/python3/dist-packages" just prepare_nfpm
    cd scripts/linux && {{nfpm}} pkg --packager deb --target "{{ sources_dir }}/dist/"

# Create Fedora package
[group("os_linux")]
fedora:
    PYTHONLIBPATH="lib64/python3.14/site-packages" just prepare_nfpm
    cd scripts/linux && {{nfpm}} pkg --packager rpm --target "{{ sources_dir }}/dist/"
