from .about import OfbQtAboutModule
from .automation import OfbQtAutomationModule
from .choose_device import OfbQtChooseDeviceModule
from .common import OfbQtCommonModule
from .device_info import OfbQtDeviceInfoModule
from .device_other import OfbQtDeviceOtherSettingsModule
from .dual_connect import OfbQtDualConnectModule
from .gestures import OfbQtGesturesModule
from .find_device import OfbQtFindDeviceModule
from .case_sound import OfbQtCaseSoundModule
from .hotkeys_module import OfbQtHotkeysModule
from .linux_related import OfbQtLinuxExtrasModule
from .sound_quality import OfbQtSoundQualityModule
from .ui_settings import OfbQtUiSettingsModule
