# Install dependencies for Flatpak build
[group("prepare"),linux]
deps_flatpak:
    flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    flatpak install -y --user org.flatpak.Builder

# Install OpenFreebuds as Flatpak package
[group("linux"),linux]
flatpak_install:
    just build || true
    mkdir -p {{flatpak_dir}}
    echo "*" > {{flatpak_dir}}/.gitignore
    flatpak run org.flatpak.Builder \
            --force-clean --user --install \
            --install-deps-from=flathub \
            --repo={{flatpak_dir}}/repo \
            --state-dir={{flatpak_dir}}/state \
            --disable-rofiles-fuse \
        {{flatpak_dir}}/builddir \
        {{sources_dir}}/scripts/flatpak/pw.mmk.OpenFreebuds.yml

# Build Flatpak package file
[group("linux"),linux]
flatpak: flatpak_install
    mkdir -p dist
    flatpak build-bundle \
        {{flatpak_dir}}/repo \
        ./dist/openfreebuds_{{version}}_{{arch()}}.flatapk \
        pw.mmk.OpenFreebuds

# Sync Python dependencies for Flatpak
[group("manage"),linux]
sync_flatpak:
    mkdir -p ./.flatpak
    python -m venv ./.flatpak/venv
    ./.flatpak/venv/bin/pip install req2flatpak==0.3.1
    # TODO: Move inside Justfile
    ./.flatpak/venv/bin/python ./scripts/bump_version.py flatpak_deps
    sed -i \
        's/--verbose --exists-action=i/--verbose --no-deps --exists-action=i/g' \
        scripts/flatpak/python3-requirements.json
