EVENT_MANAGER_STATE_CHANGED = "ofb_man_state_changed"
EVENT_MANAGER_SCAN_COMPLETE = "ofb_man_scan_complete"
EVENT_MANAGER_CLOSE = "ofb_man_close"
EVENT_SPP_CLOSED = "spp_device_closed"
EVENT_SPP_RECV = "spp_device_package_recv"
EVENT_DEVICE_PROP_CHANGED = "spp_device_prop_changed"
EVENT_UI_UPDATE_REQUIRED = "applet_ui_update"
