import "./vars.just"
import "./cc_linux.just"

# Make windows installer
[group("os_windows"),windows]
win32_installer: build
    New-Item -ItemType Directory -Force -Path ./dist
    cd ./scripts/windows; & {{pyinstaller}} openfreebuds.spec
    New-Item -ItemType Directory -Force -Path {{ nsis_builddir }}
    cd ./scripts/windows; & 'C:\Program Files (x86)\NSIS\Bin\makensis.exe' openfreebuds.nsi
    mv -Force \
        {{ nsis_builddir }}/openfreebuds.install.exe \
        ./dist/openfreebuds_{{version}}_{{arch()}}_windows.exe

# Make windows portable executable
[group("os_windows"),windows]
win32_portable:
    New-Item -ItemType Directory -Force -Path ./dist
    New-Item -ItemType Directory -Force -Path {{ nsis_builddir }}
    cd ./scripts/windows; & {{pyinstaller}} openfreebuds_portable.spec
    mv -Force \
        {{ pyinstaller_distdir }}/openfreebuds_portable.exe \
        ./dist/openfreebuds_{{version}}_{{arch()}}_windows_portable.exe

# Make windows installer and portable
[group("os_windows"),windows,linux]
win32: win32_installer win32_portable
