from .action_dual_tap import OfbHuaweiActionDoubleTapHandler
from .action_triple_tap import OfbHuaweiActionTripleTapHandler
from .action_long_tap import OfbHuaweiActionLongTapHandler
from .action_long_tap import OfbHuaweiActionLongTapHandler
from .action_long_tap_split import OfbHuaweiActionLongTapSplitHandler
from .action_power_button import OfbHuaweiActionsPowerButtonHandler
from .action_swipe_gesture import OfbHuaweiActionSwipeGestureHandler
from .anc import OfbHuaweiAncHandler, OfbHuaweiAncLegacyChangeHandler
from .battery import OfbHuaweiBatteryHandler
from .config_auto_pause import OfbHuaweiConfigAutoPauseHandler
from .config_equalizer import OfbHuaweiEqualizerPresetHandler
from .sound_quality_preference import OfnHuaweiSoundQualityPreferenceHandler
from .info import OfbHuaweiInfoHandler
from .logs import OfbHuaweiLogsHandler
from .service_language import OfbHuaweiVoiceLanguageHandler
from .state_in_ear import OfbHuaweiStateInEarHandler
from .low_latency import OfbHuaweiLowLatencyPreferenceHandler
from .dual_connect import OfbHuaweiDualConnectHandler
