services:
  cicd_linux:
    container_name: cicd_linux
    build:
      context: .
      dockerfile: ./Dockerfile.linux
    environment:
      PATH: "/usr/bin:/usr/sbin:/root/.local/bin"
      DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/0/bus
    volumes:
      # Signing keys
      - ${HOME}/.gnupg:/root/.gnupg:z
    # required for flatpak build
    privileged: true

  cicd_wine:
    container_name: cicd_wine
    build:
      context: .
      dockerfile: ./Dockerfile.wine
    environment:
      PATH: "/usr/bin:/usr/sbin:/root/.local/bin"

  cicd_wine_arm64:
    container_name: cicd_wine_arm64
    build:
      context: .
      dockerfile: ./Dockerfile.wine_arm64
    environment:
      PATH: "/usr/bin:/usr/sbin:/root/.local/bin"

  controller:
    container_name: cicd_controller
    build:
      context: .
      dockerfile: ./Dockerfile.linux
    hostname: controller
    security_opt: 
      - label=disable
    environment:
      HOST_UID: "${HOST_UID}"
    volumes:
      # Source code
      - ../../:/app:z
      # To interact with containers
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      # To manage VMs
      - /run/libvirt:/run/libvirt:ro
      # SSH keys (for external hosts access)
      - ${HOME}/.ssh:/ssh_config:roZ
    depends_on:
      - cicd_linux
      - cicd_wine
      - cicd_wine_arm64
